import { dirname } from 'node:path';
import { writeFileAtomic } from '../platform/atomic-write';
import type { AppPaths } from './app-paths';
import type { AppConfig, AppPreferences, TenantBrand } from './schema';
import { secretKeyForApp } from './schema';

/**
 * Build an AppConfig that reads the App Secret from the encrypted local
 * keystore through the bridge's exec-provider SecretRef.
 */
export async function buildEncryptedAccountConfig(
  appId: string,
  tenant: TenantBrand,
  preferences: AppPreferences | undefined,
  appPaths: Pick<AppPaths, 'secretsGetterScript'> & { rootDir?: string },
): Promise<AppConfig> {
  const wrapperPath = await ensureSecretsGetterWrapper(appPaths);
  return {
    accounts: {
      app: {
        id: appId,
        secret: {
          source: 'exec',
          provider: 'bridge',
          id: secretKeyForApp(appId),
        },
        tenant,
      },
    },
    secrets: {
      providers: {
        bridge: {
          source: 'exec',
          command: wrapperPath,
          // The wrapper has args baked in; pass none here.
          args: [],
        },
      },
    },
    ...(preferences ? { preferences } : {}),
  };
}

/**
 * Write (or rewrite) the secrets-getter wrapper to point at the currently-
 * running node + bridge entry script. Always rewrites — node path can move
 * between bridge runs (nvm version switch, re-install) and the wrapper
 * must stay in sync. Returns the wrapper path.
 *
 * File perms 0700 so audit's `world/group-writable` check passes (and
 * extra restrictive — wrapper is a private user resource).
 */
export async function ensureSecretsGetterWrapper(
  appPaths: Pick<AppPaths, 'secretsGetterScript'> & { rootDir?: string },
  opts: {
    nodePath?: string;
    bridgeEntry?: string;
  } = {},
): Promise<string> {
  const wrapperPath = appPaths.secretsGetterScript;
  const node = opts.nodePath ?? process.execPath;
  const bridgeEntry = opts.bridgeEntry ?? process.argv[1] ?? '';
  const rootDir = appPaths.rootDir ?? dirname(appPaths.secretsGetterScript);

  // Single-quoted shell-safe strings: escape any embedded single quotes.
  const sq = (s: string): string => `'${s.replace(/'/g, `'\\''`)}'`;
  const content =
    `#!/bin/sh\n` +
    `# Auto-generated by lark-bot-bridge. Do not edit.\n` +
    `# Forwards exec-provider requests to: node bridge secrets get\n` +
    `LARK_CHANNEL_HOME=${sq(rootDir)} exec ${sq(node)} ${sq(bridgeEntry)} secrets get "$@"\n`;

  await writeFileAtomic(wrapperPath, content, { mode: 0o700 });
  return wrapperPath;
}
